### ISSUE TITLE
Failed at parse_runs

### ISSUE THREAD

**Issue by hbbrandao** [mirnylab/distiller-nf#43]
output:
```
ERROR ~ Error executing process > 'parse_runs (library:strain_2 run:lane1)'

Caused by:
  Cannot invoke method toBoolean() on null object


Source block:
  dropsam_flag = params['map'].get('drop_sam','false').toBoolean() ? '--drop-sam' : ''
  dropreadid_flag = params['map'].get('drop_readid','false').toBoolean() ? '--drop-readid' : ''
  dropseq_flag = params['map'].get('drop_seq','false').toBoolean() ? '--drop-seq' : ''
  stats_command = (params.get('do_stats', 'true').toBoolean() ?
      "pairsamtools stats ${library}.${run}.pairsam.gz -o ${library}.${run}.stats" :
      "touch ${library}.${run}.stats" )
  n_parse_processes = (int)Math.ceil(task.cpus / 2)
  n_parse_processes = n_parse_processes < 1 ? 1 : n_parse_processes
  if( isSingleFile(bam))
      """
      mkdir ./tmp4sort
      pairsamtools parse ${dropsam_flag} ${dropreadid_flag} ${dropseq_flag} \
          -c ${chrom_sizes}  ${bam} \
              | pairsamtools sort --nproc ${task.cpus} \
                                  -o ${library}.${run}.pairsam.gz \
                                  --tmpdir ./tmp4sort \
              | cat
  
      rm -rf ./tmp4sort
  
      ${stats_command}
      """
  else 
      """
      mkdir ./tmp4sort
      mkdir ./tmp_pairsam
      parallel -P${n_parse_processes} 'pairsamtools parse \
          ${dropsam_flag} ${dropseq_flag} ${dropreadid_flag} -c ${chrom_sizes} {} \
          | pairsamtools sort --nproc 4 \
                              -o ./tmp_pairsam/{}.pairsam.gz \
                              --tmpdir ./tmp4sort ' ::: ${bam}
  
      pairsamtools merge ./tmp_pairsam/* --nproc ${task.cpus} -o ${library}.${run}.pairsam.gz
  
      rm -rf ./tmp4sort
      rm -rf ./tmp_pairsam
  
      ${stats_command}
      """
```
project.yml
```
do_fastqc: True
do_stats: True
    

# Fastqs can be provided as:
# -- a pairs of relative/absolute paths
# -- sra:<SRA_NUMBER>, optionally followed by the indices of the first and
# the last entry in the SRA in the form of "?start=<first>&end=<last>
# [to implement] -- as a path to a folder with fastqs '<base_folder>', with the structure 
# <base_folder>/<library_name>/<run_name>/, with each folder containing only
# two fastq.gz files
input:
    raw_reads_paths:
        strain_1:
            lane1:
                - /home/hbrandao/Documents/Rudner_data/test_distiller/fastq/SRR2002581_1.fastq.gz
                - /home/hbrandao/Documents/Rudner_data/test_distiller/fastq/SRR2002581_2.fastq.gz  

        strain_2:
            lane1:
                - /home/hbrandao/Documents/Rudner_data/test_distiller/fastq/SRR2002583_2.fastq.gz  
                - /home/hbrandao/Documents/Rudner_data/test_distiller/fastq/SRR2002584_1.fastq.gz


    library_groups:
        PY79:
            - strain_1
            - strain_2

    genome:
        assembly: 'bacillus'
        bwa_index_wildcard: '/home/hbrandao/Documents/Rudner_data/PY79_genome/bwa_index/NC_022898.1.fa.*'
        chrom_sizes_path: '/home/hbrandao/Documents/Rudner_data/PY79_genome/bwa_index/PY79.chrom.sizes'

map:
    chunksize: 6000
    #drop_sam: False
    #drop_readid: False
    #drop_seq: False

filter:
    pcr_dups_max_mismatch_bp: 3

bin:
    resolutions:
        - 1000000
        - 400000
        - 200000
        - 100000
        - 40000
        - 20000
        - 10000

intermediates:
    base_dir: './intermediates/'
    dirs:
        downloaded_fastqs: 'downloaded_fastqs/'
        fastq_chunks: 'fastq_chunks'
        bam_run: 'bam/run'
        pairsam_run: 'pairsam/run'
        pairsam_library: 'pairsam/library'

output:
    base_dir: '/home/hbrandao/Documents/Rudner_data/test_distiller/output/'
    dirs:
        fastqc: 'fastqc/'
        pairs_library: 'pairs/library/'
        stats_run: 'stats/run/'
        stats_library: 'stats/library/'
        stats_library_group: 'stats/library_group/'
        coolers_library: 'coolers/library/'
        coolers_library_group: 'coolers/library_group/'
        bams_library: 'bams/library_group/'
```
