### ISSUE TITLE
Implicit run names when specifying SRA links

### ISSUE THREAD

**Issue by nvictus** [mirnylab/distiller-nf#74]
It might be nice to support this:
```
input:
    raw_reads_paths:
        HiC_ES_1:
            - sra:SRR5339748
            - sra:SRR5339749
            - sra:SRR5339750
            - sra:SRR5339751
            - sra:SRR5339752
            - sra:SRR5339753
...
```

as an alternative to this:
```
input:
    raw_reads_paths:
        HiC_ES_1:
            run1:
                - sra:SRR5339748
            run2:
                - sra:SRR5339749
            run3:
                - sra:SRR5339750
            run4:
                - sra:SRR5339751
            run5:
                - sra:SRR5339752
            run6:
                - sra:SRR5339753
...
```
